name: Build OpenOCD for Windows, MacOS, and Linux

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build-macos-x86:
    runs-on: macos-13
    steps:
      - name: Ensure architecture is x86_64
        run: |
          if [[ "$(uname -m)" != "x86_64" ]]; then
            echo "Error: Expected x86_64 architecture but got $(uname -m)" >&2
            exit 1
          fi
      - uses: actions/checkout@v4
      - name: install deps
        run: brew install automake texinfo coreutils
      - name: Build and Upload OpenOCD artifact
        uses: ./.github/actions/common-build-steps
        with:
          arch: macos-x86

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Ensure architecture is arm64
        run: |
          if [[ "$(uname -m)" != "arm64" ]]; then
            echo "Error: Expected arm64 architecture but got $(uname -m)" >&2
            exit 1
          fi
      - uses: actions/checkout@v4
      - name: install deps
        run: brew install automake libtool texinfo coreutils
      - name: Build and Upload OpenOCD artifact
        uses: ./.github/actions/common-build-steps
        with:
          arch: macos-arm64

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: sudo apt-get install libudev-dev systemd --force-yes -y
      - name: Build and Upload OpenOCD artifact
        uses: ./.github/actions/common-build-steps
        with:
          arch: linux

  build-windows:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install deps
        run: sudo apt-get install libtool-bin libudev-dev gcc-mingw-w64-i686
      - name: Build and Upload OpenOCD artifact
        uses: ./.github/actions/common-build-steps
        with:
          arch: windows

  release:
    needs: [build-macos-x86, build-macos-arm64, build-linux, build-windows]
    runs-on: ubuntu-22.04
    steps:
      - name: Download build OpenOCD binaries
        uses: actions/download-artifact@v4
        with:
          path: tool-openocd-esp32
      - run: |
          curl -O https://raw.githubusercontent.com/Jason2866/openocd-esp32/m1/package.json
          cp package.json tool-openocd-esp32/openocd-macos-x86
          cp package.json tool-openocd-esp32/openocd-macos-arm64
          cp package.json tool-openocd-esp32/openocd-linux
          cp package.json tool-openocd-esp32/openocd-windows
          tar -zcf openocd-macos-x86.tar.gz -C tool-openocd-esp32/openocd-macos-x86 .
          tar -zcf openocd-macos-arm64.tar.gz -C tool-openocd-esp32/openocd-macos-arm64 .
          tar -zcf openocd-linux.tar.gz -C tool-openocd-esp32/openocd-linux .
          tar -zcf openocd-windows.tar.gz -C tool-openocd-esp32/openocd-windows .
      - uses: jason2866/action-gh-release@v1.3
        with:
          tag_name: ${{ github.run_number }}
          prerelease: true
          files: |
            openocd-macos-x86.tar.gz
            openocd-macos-arm64.tar.gz
            openocd-linux.tar.gz
            openocd-windows.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
