# Manually started action to build OpenOCD for Mac and upload to an artifact

name: Build MacOS ARM
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4.0'

    - name: Build OpenOCD
      run: |
        uname -a
        brew update
        brew install bash libtool automake libusb hidapi jimtcl
        git clone https://github.com/Jason2866/openocd-esp32.git
        pushd openocd-esp32
        git checkout m1
        # Remove TEXI warning
        grep -v raggedright doc/openocd.texi > p2
        mv p2 doc/openocd.texi
        bash bootstrap
        ./configure --prefix=/tmp/openocd
        make -j
        make install
        popd
        tar cvf openocd.darwin-arm64.tar -C /tmp openocd

    - name: Upload OpenOCD
      uses: actions/upload-artifact@v4
      with:
        name: openocd.darwin-arm64.tar
        path: openocd.darwin-arm64.tar

    - name: Release
      uses: jason2866/action-gh-release@v1.3
      with:
        tag_name: ${{ github.run_number }}
        prerelease: true
        files: |
          openocd.darwin-arm64.tar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
